### PR TITLE
Implemented fake_flatten.

### PR DESCRIPTION
**Pull request by stuartskelton**
This is my attempt at fake_flatten as described in #3.

This will also flatten hash refs, and plain array_ref and hash_refs.

so something horrific like:

`
warn fake_join(',',fake_flatten(fake_array(fake_int(1,3),fake_pick(fake_flatten([qw(1 2 3 4 5)])))))->();
`

 is possible.

### CODE REVIEW

**Comment by stuartskelton** [comment]
as a side note, if this is in place, fake_char (#2) would be.. (i seem to have merged both fake_chars and fake_printable but it would be trivial to separate)

```
sub fake_chars {
    my ($count, $charactors) = @_;
    # default to printable ascii, not including the space (32) and the delete (127)
    $charactors =  sub {chr(fake_int(33, 126)->())} unless $charactors;

    $charactors = fake_pick(@$charactors) if ref($charactors) eq 'ARRAY';

    die '' unless $charactors;

    return sub {
        fake_join( '', fake_flatten(fake_array( _transform($count), $charactors )))->();
    }
}


for (1..10){
    say fake_chars(10)->();
    say fake_chars(fake_int(1,10))->();
}
```

**Comment by xdg** [comment]
Thanks.  I've been busy with the start of the school year, but hope to get a look at this soon.

**Comment by stuartskelton** [comment]
No worries, I've been busy too.

**Comment by stuartskelton** [comment]
Now the school year is well under way, would you mine taking a look to see if this fits please.

**Comment by xdg** [comment]
Sorry this fell off my radar for so long.  Rebased and merged in c3a0daf

**Comment by stuartskelton** [comment]
no worries,  that was a long school year ;D

**Pull request closed without merging**
